--
-- PostgreSQL database dump
--

\restrict wzztxEO7W3dJrQ4UHFY3bwdKI6GGha8heMQiprmyjVXqzSTV5PKf6KXbzEdhbjg

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-29 09:56:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16388)
-- Name: bodegas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bodegas (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    estado integer NOT NULL
);


ALTER TABLE public.bodegas OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16387)
-- Name: bodegas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bodegas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bodegas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16398)
-- Name: monedas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.monedas (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    estado integer NOT NULL
);


ALTER TABLE public.monedas OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16397)
-- Name: monedas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.monedas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.monedas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16424)
-- Name: productos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productos (
    id bigint NOT NULL,
    codigo character varying(255),
    nombre character varying(255),
    bodega_id bigint,
    sucursal_id bigint,
    moneda_id bigint,
    precio integer,
    material text,
    descripcion text,
    estado integer
);


ALTER TABLE public.productos OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16423)
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16408)
-- Name: sucursales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sucursales (
    id bigint NOT NULL,
    bodegas_id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    estado integer NOT NULL
);


ALTER TABLE public.sucursales OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16407)
-- Name: sucursales_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sucursales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sucursales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5031 (class 0 OID 16388)
-- Dependencies: 220
-- Data for Name: bodegas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bodegas (id, nombre, estado) FROM stdin;
1	Bodega 1	1
2	Bodega 2	1
\.


--
-- TOC entry 5033 (class 0 OID 16398)
-- Dependencies: 222
-- Data for Name: monedas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.monedas (id, nombre, estado) FROM stdin;
1	PESO	1
2	DÓLAR	1
3	EURO	1
\.


--
-- TOC entry 5037 (class 0 OID 16424)
-- Dependencies: 226
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.productos (id, codigo, nombre, bodega_id, sucursal_id, moneda_id, precio, material, descripcion, estado) FROM stdin;
10	PROD01K	Set Comedor	1	1	2	1500	Plástico,Metal	Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.	1
\.


--
-- TOC entry 5035 (class 0 OID 16408)
-- Dependencies: 224
-- Data for Name: sucursales; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sucursales (id, bodegas_id, nombre, estado) FROM stdin;
1	1	Sucursal 1	1
2	1	Sucursal 2	1
3	2	Sucursal 3	1
4	2	Sucursal 4	1
5	2	Sucursal 5	1
\.


--
-- TOC entry 5043 (class 0 OID 0)
-- Dependencies: 219
-- Name: bodegas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bodegas_id_seq', 3, false);


--
-- TOC entry 5044 (class 0 OID 0)
-- Dependencies: 221
-- Name: monedas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.monedas_id_seq', 4, false);


--
-- TOC entry 5045 (class 0 OID 0)
-- Dependencies: 225
-- Name: productos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.productos_id_seq', 10, true);


--
-- TOC entry 5046 (class 0 OID 0)
-- Dependencies: 223
-- Name: sucursales_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sucursales_id_seq', 6, false);


--
-- TOC entry 4872 (class 2606 OID 16395)
-- Name: bodegas bodegas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bodegas
    ADD CONSTRAINT bodegas_pkey PRIMARY KEY (id);


--
-- TOC entry 4874 (class 2606 OID 16405)
-- Name: monedas monedas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monedas
    ADD CONSTRAINT monedas_pkey PRIMARY KEY (id);


--
-- TOC entry 4878 (class 2606 OID 16431)
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- TOC entry 4876 (class 2606 OID 16416)
-- Name: sucursales sucursales_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sucursales
    ADD CONSTRAINT sucursales_pkey PRIMARY KEY (id);


--
-- TOC entry 4880 (class 2606 OID 16432)
-- Name: productos fk_productos_bodega; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fk_productos_bodega FOREIGN KEY (bodega_id) REFERENCES public.bodegas(id);


--
-- TOC entry 4881 (class 2606 OID 16442)
-- Name: productos fk_productos_moneda; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fk_productos_moneda FOREIGN KEY (moneda_id) REFERENCES public.monedas(id);


--
-- TOC entry 4882 (class 2606 OID 16437)
-- Name: productos fk_productos_sucursal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fk_productos_sucursal FOREIGN KEY (sucursal_id) REFERENCES public.sucursales(id);


--
-- TOC entry 4879 (class 2606 OID 16417)
-- Name: sucursales fk_sucursales_bodegas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sucursales
    ADD CONSTRAINT fk_sucursales_bodegas FOREIGN KEY (bodegas_id) REFERENCES public.bodegas(id) ON UPDATE CASCADE ON DELETE CASCADE;


-- Completed on 2026-06-29 09:56:57

--
-- PostgreSQL database dump complete
--

\unrestrict wzztxEO7W3dJrQ4UHFY3bwdKI6GGha8heMQiprmyjVXqzSTV5PKf6KXbzEdhbjg

